"""
DAG to process taxi data (yellow and green) from GitHub to BigQuery.
Equivalent to the 08_gcp_taxi.yaml flow in Kestra.

This DAG allows manual processing by specifying:
- taxi: 'yellow' or 'green'
- year: year (e.g., '2019', '2020', '2021')
- month: month (e.g., '01', '02', ..., '12')

Usage: Trigger DAG with config JSON:
{
  "taxi": "green",
  "year": "2021",
  "month": "01"
}
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator, BranchPythonOperator
from airflow.providers.google.cloud.operators.bigquery import BigQueryExecuteQueryOperator
from airflow.providers.google.cloud.transfers.local_to_gcs import LocalFilesystemToGCSOperator
from airflow.utils.task_group import TaskGroup
import os

# GCP configuration variables
GCP_PROJECT_ID = os.getenv('GCP_PROJECT_ID', 'your-gcp-project-id')
GCP_DATASET = os.getenv('GCP_DATASET', 'your-dataset-name')
GCP_BUCKET_NAME = os.getenv('GCP_BUCKET_NAME', 'your-bucket-name')
GCP_LOCATION = os.getenv('GCP_LOCATION', 'us-central1')

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

def branch_on_taxi_type(**context):
    """Branch operator to decide which pipeline to execute based on taxi type"""
    taxi = context['dag_run'].conf.get('taxi', 'green')
    if taxi == 'yellow':
        return 'yellow_pipeline.bq_yellow_tripdata'
    else:
        return 'green_pipeline.bq_green_tripdata'

def cleanup_local_file(**context):
    """Cleans up the local files after uploading to GCS"""
    taxi = context['dag_run'].conf.get('taxi', 'green')
    year = context['dag_run'].conf.get('year', '2019')
    month = context['dag_run'].conf.get('month', '01')
    file_name = f"{taxi}_tripdata_{year}-{month}.csv"
    csv_path = f"/tmp/{file_name}"
    gz_path = f"/tmp/{file_name}.gz"
    
    if os.path.exists(csv_path):
        os.remove(csv_path)
        print(f"File {csv_path} deleted")
    if os.path.exists(gz_path):
        os.remove(gz_path)
        print(f"File {gz_path} deleted")

# Main DAG
with DAG(
    '08_gcp_taxi',
    default_args=default_args,
    description='Process taxi data from GitHub to BigQuery (manual version)',
    schedule_interval=None,  # Manual trigger only
    start_date=datetime(2024, 1, 1),
    catchup=False,
    params={
        'taxi': 'green',
        'year': '2019',
        'month': '01'
    },
    tags=['gcp', 'taxi', 'bigquery', 'manual'],
) as dag:

    # Task to download and decompress the file
    extract = BashOperator(
        task_id='extract',
        bash_command="""
        TAXI="{{ dag_run.conf.get('taxi', 'green') }}"
        YEAR="{{ dag_run.conf.get('year', '2019') }}"
        MONTH="{{ dag_run.conf.get('month', '01') }}"
        FILE_NAME="${TAXI}_tripdata_${YEAR}-${MONTH}.csv"
        GZ_FILE="${FILE_NAME}.gz"
        
        # Download the compressed file and save it
        wget -q "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/${TAXI}/${GZ_FILE}" -O /tmp/${GZ_FILE}
        echo "Compressed file downloaded: /tmp/${GZ_FILE}"
        ls -lh /tmp/${GZ_FILE}
        
        # Decompress the file
        gunzip -c /tmp/${GZ_FILE} > /tmp/${FILE_NAME}
        echo "File decompressed: /tmp/${FILE_NAME}"
        ls -lh /tmp/${FILE_NAME}
        """,
    )

    # Task to upload to GCS
    upload_to_gcs = LocalFilesystemToGCSOperator(
        task_id='upload_to_gcs',
        src='/tmp/{{ dag_run.conf.get("taxi", "green") }}_tripdata_{{ dag_run.conf.get("year", "2019") }}-{{ dag_run.conf.get("month", "01") }}.csv',
        dst='{{ dag_run.conf.get("taxi", "green") }}_tripdata_{{ dag_run.conf.get("year", "2019") }}-{{ dag_run.conf.get("month", "01") }}.csv',
        bucket=GCP_BUCKET_NAME,
    )

    # Branch operator to decide which pipeline to execute
    branch_task = BranchPythonOperator(
        task_id='branch_on_taxi_type',
        python_callable=branch_on_taxi_type,
    )

    # ========== YELLOW TAXI PIPELINE ==========
    with TaskGroup('yellow_pipeline') as yellow_pipeline:
        
        # Create main yellow_tripdata table
        bq_yellow_tripdata = BigQueryExecuteQueryOperator(
            task_id='bq_yellow_tripdata',
            sql=f"""
            CREATE TABLE IF NOT EXISTS `{GCP_PROJECT_ID}.{GCP_DATASET}.yellow_tripdata`
            (
                unique_row_id BYTES OPTIONS (description = 'A unique identifier for the trip, generated by hashing key trip attributes.'),
                filename STRING OPTIONS (description = 'The source filename from which the trip data was loaded.'),      
                VendorID STRING OPTIONS (description = 'A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.'),
                tpep_pickup_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was engaged'),
                tpep_dropoff_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was disengaged'),
                passenger_count INTEGER OPTIONS (description = 'The number of passengers in the vehicle. This is a driver-entered value.'),
                trip_distance NUMERIC OPTIONS (description = 'The elapsed trip distance in miles reported by the taximeter.'),
                RatecodeID STRING OPTIONS (description = 'The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride'),
                store_and_fwd_flag STRING OPTIONS (description = 'This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka "store and forward," because the vehicle did not have a connection to the server. TRUE = store and forward trip, FALSE = not a store and forward trip'),
                PULocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was engaged'),
                DOLocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was disengaged'),
                payment_type INTEGER OPTIONS (description = 'A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip'),
                fare_amount NUMERIC OPTIONS (description = 'The time-and-distance fare calculated by the meter'),
                extra NUMERIC OPTIONS (description = 'Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges'),
                mta_tax NUMERIC OPTIONS (description = '$0.50 MTA tax that is automatically triggered based on the metered rate in use'),
                tip_amount NUMERIC OPTIONS (description = 'Tip amount. This field is automatically populated for credit card tips. Cash tips are not included.'),
                tolls_amount NUMERIC OPTIONS (description = 'Total amount of all tolls paid in trip.'),
                improvement_surcharge NUMERIC OPTIONS (description = '$0.30 improvement surcharge assessed on hailed trips at the flag drop. The improvement surcharge began being levied in 2015.'),
                total_amount NUMERIC OPTIONS (description = 'The total amount charged to passengers. Does not include cash tips.'),
                congestion_surcharge NUMERIC OPTIONS (description = 'Congestion surcharge applied to trips in congested zones')
            )
            PARTITION BY DATE(tpep_pickup_datetime);
            """,
            use_legacy_sql=False,
            location=GCP_LOCATION,
        )

        # Create external yellow table
        bq_yellow_table_ext = BigQueryExecuteQueryOperator(
            task_id='bq_yellow_table_ext',
            sql=f"""
            CREATE OR REPLACE EXTERNAL TABLE `{GCP_PROJECT_ID}.{GCP_DATASET}.{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}_{{{{ dag_run.conf.get('month', '01') }}}}_ext`
            (
                VendorID STRING,
                tpep_pickup_datetime TIMESTAMP,
                tpep_dropoff_datetime TIMESTAMP,
                passenger_count INTEGER,
                trip_distance NUMERIC,
                RatecodeID STRING,
                store_and_fwd_flag STRING,
                PULocationID STRING,
                DOLocationID STRING,
                payment_type INTEGER,
                fare_amount NUMERIC,
                extra NUMERIC,
                mta_tax NUMERIC,
                tip_amount NUMERIC,
                tolls_amount NUMERIC,
                improvement_surcharge NUMERIC,
                total_amount NUMERIC,
                congestion_surcharge NUMERIC
            )
            OPTIONS (
                format = 'CSV',
                uris = ['gs://{GCP_BUCKET_NAME}/{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}-{{{{ dag_run.conf.get('month', '01') }}}}.csv'],
                skip_leading_rows = 1,
                ignore_unknown_values = TRUE
            );
            """,
            use_legacy_sql=False,
            location=GCP_LOCATION,
        )

        # Create temporary yellow table
        bq_yellow_table_tmp = BigQueryExecuteQueryOperator(
            task_id='bq_yellow_table_tmp',
            sql=f"""
            CREATE OR REPLACE TABLE `{GCP_PROJECT_ID}.{GCP_DATASET}.{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}_{{{{ dag_run.conf.get('month', '01') }}}}`
            AS
            SELECT
              MD5(CONCAT(
                COALESCE(CAST(VendorID AS STRING), ""),
                COALESCE(CAST(tpep_pickup_datetime AS STRING), ""),
                COALESCE(CAST(tpep_dropoff_datetime AS STRING), ""),
                COALESCE(CAST(PULocationID AS STRING), ""),
                COALESCE(CAST(DOLocationID AS STRING), "")
              )) AS unique_row_id,
              "{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}-{{{{ dag_run.conf.get('month', '01') }}}}.csv" AS filename,
              *
            FROM `{GCP_PROJECT_ID}.{GCP_DATASET}.{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}_{{{{ dag_run.conf.get('month', '01') }}}}_ext`;
            """,
            use_legacy_sql=False,
            location=GCP_LOCATION,
        )

        # Merge yellow data
        bq_yellow_merge = BigQueryExecuteQueryOperator(
            task_id='bq_yellow_merge',
            sql=f"""
            MERGE INTO `{GCP_PROJECT_ID}.{GCP_DATASET}.yellow_tripdata` T
            USING `{GCP_PROJECT_ID}.{GCP_DATASET}.{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}_{{{{ dag_run.conf.get('month', '01') }}}}` S
            ON T.unique_row_id = S.unique_row_id
            WHEN NOT MATCHED THEN
              INSERT (unique_row_id, filename, VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge)
              VALUES (S.unique_row_id, S.filename, S.VendorID, S.tpep_pickup_datetime, S.tpep_dropoff_datetime, S.passenger_count, S.trip_distance, S.RatecodeID, S.store_and_fwd_flag, S.PULocationID, S.DOLocationID, S.payment_type, S.fare_amount, S.extra, S.mta_tax, S.tip_amount, S.tolls_amount, S.improvement_surcharge, S.total_amount, S.congestion_surcharge);
            """,
            use_legacy_sql=False,
            location=GCP_LOCATION,
        )

        bq_yellow_tripdata >> bq_yellow_table_ext >> bq_yellow_table_tmp >> bq_yellow_merge

    # ========== GREEN TAXI PIPELINE ==========
    with TaskGroup('green_pipeline') as green_pipeline:
        
        # Create main green_tripdata table
        bq_green_tripdata = BigQueryExecuteQueryOperator(
            task_id='bq_green_tripdata',
            sql=f"""
            CREATE TABLE IF NOT EXISTS `{GCP_PROJECT_ID}.{GCP_DATASET}.green_tripdata`
            (
                unique_row_id BYTES OPTIONS (description = 'A unique identifier for the trip, generated by hashing key trip attributes.'),
                filename STRING OPTIONS (description = 'The source filename from which the trip data was loaded.'),      
                VendorID STRING OPTIONS (description = 'A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.'),
                lpep_pickup_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was engaged'),
                lpep_dropoff_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was disengaged'),
                store_and_fwd_flag STRING OPTIONS (description = 'This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka "store and forward," because the vehicle did not have a connection to the server. Y= store and forward trip N= not a store and forward trip'),
                RatecodeID STRING OPTIONS (description = 'The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride'),
                PULocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was engaged'),
                DOLocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was disengaged'),
                passenger_count INT64 OPTIONS (description = 'The number of passengers in the vehicle. This is a driver-entered value.'),
                trip_distance NUMERIC OPTIONS (description = 'The elapsed trip distance in miles reported by the taximeter.'),
                fare_amount NUMERIC OPTIONS (description = 'The time-and-distance fare calculated by the meter'),
                extra NUMERIC OPTIONS (description = 'Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges'),
                mta_tax NUMERIC OPTIONS (description = '$0.50 MTA tax that is automatically triggered based on the metered rate in use'),
                tip_amount NUMERIC OPTIONS (description = 'Tip amount. This field is automatically populated for credit card tips. Cash tips are not included.'),
                tolls_amount NUMERIC OPTIONS (description = 'Total amount of all tolls paid in trip.'),
                ehail_fee NUMERIC,
                improvement_surcharge NUMERIC OPTIONS (description = '$0.30 improvement surcharge assessed on hailed trips at the flag drop. The improvement surcharge began being levied in 2015.'),
                total_amount NUMERIC OPTIONS (description = 'The total amount charged to passengers. Does not include cash tips.'),
                payment_type INTEGER OPTIONS (description = 'A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip'),
                trip_type STRING OPTIONS (description = 'A code indicating whether the trip was a street-hail or a dispatch that is automatically assigned based on the metered rate in use but can be altered by the driver. 1= Street-hail 2= Dispatch'),
                congestion_surcharge NUMERIC OPTIONS (description = 'Congestion surcharge applied to trips in congested zones')
            )
            PARTITION BY DATE(lpep_pickup_datetime);
            """,
            use_legacy_sql=False,
            location=GCP_LOCATION,
        )

        # Create external green table
        bq_green_table_ext = BigQueryExecuteQueryOperator(
            task_id='bq_green_table_ext',
            sql=f"""
            CREATE OR REPLACE EXTERNAL TABLE `{GCP_PROJECT_ID}.{GCP_DATASET}.{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}_{{{{ dag_run.conf.get('month', '01') }}}}_ext`
            (
                VendorID STRING,
                lpep_pickup_datetime TIMESTAMP,
                lpep_dropoff_datetime TIMESTAMP,
                store_and_fwd_flag STRING,
                RatecodeID STRING,
                PULocationID STRING,
                DOLocationID STRING,
                passenger_count INT64,
                trip_distance NUMERIC,
                fare_amount NUMERIC,
                extra NUMERIC,
                mta_tax NUMERIC,
                tip_amount NUMERIC,
                tolls_amount NUMERIC,
                ehail_fee NUMERIC,
                improvement_surcharge NUMERIC,
                total_amount NUMERIC,
                payment_type INTEGER,
                trip_type STRING,
                congestion_surcharge NUMERIC
            )
            OPTIONS (
                format = 'CSV',
                uris = ['gs://{GCP_BUCKET_NAME}/{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}-{{{{ dag_run.conf.get('month', '01') }}}}.csv'],
                skip_leading_rows = 1,
                ignore_unknown_values = TRUE
            );
            """,
            use_legacy_sql=False,
            location=GCP_LOCATION,
        )

        # Create temporary green table
        bq_green_table_tmp = BigQueryExecuteQueryOperator(
            task_id='bq_green_table_tmp',
            sql=f"""
            CREATE OR REPLACE TABLE `{GCP_PROJECT_ID}.{GCP_DATASET}.{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}_{{{{ dag_run.conf.get('month', '01') }}}}`
            AS
            SELECT
              MD5(CONCAT(
                COALESCE(CAST(VendorID AS STRING), ""),
                COALESCE(CAST(lpep_pickup_datetime AS STRING), ""),
                COALESCE(CAST(lpep_dropoff_datetime AS STRING), ""),
                COALESCE(CAST(PULocationID AS STRING), ""),
                COALESCE(CAST(DOLocationID AS STRING), "")
              )) AS unique_row_id,
              "{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}-{{{{ dag_run.conf.get('month', '01') }}}}.csv" AS filename,
              *
            FROM `{GCP_PROJECT_ID}.{GCP_DATASET}.{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}_{{{{ dag_run.conf.get('month', '01') }}}}_ext`;
            """,
            use_legacy_sql=False,
            location=GCP_LOCATION,
        )

        # Merge green data
        bq_green_merge = BigQueryExecuteQueryOperator(
            task_id='bq_green_merge',
            sql=f"""
            MERGE INTO `{GCP_PROJECT_ID}.{GCP_DATASET}.green_tripdata` T
            USING `{GCP_PROJECT_ID}.{GCP_DATASET}.{{{{ dag_run.conf.get('taxi', 'green') }}}}_tripdata_{{{{ dag_run.conf.get('year', '2019') }}}}_{{{{ dag_run.conf.get('month', '01') }}}}` S
            ON T.unique_row_id = S.unique_row_id
            WHEN NOT MATCHED THEN
              INSERT (unique_row_id, filename, VendorID, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, RatecodeID, PULocationID, DOLocationID, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge)
              VALUES (S.unique_row_id, S.filename, S.VendorID, S.lpep_pickup_datetime, S.lpep_dropoff_datetime, S.store_and_fwd_flag, S.RatecodeID, S.PULocationID, S.DOLocationID, S.passenger_count, S.trip_distance, S.fare_amount, S.extra, S.mta_tax, S.tip_amount, S.tolls_amount, S.ehail_fee, S.improvement_surcharge, S.total_amount, S.payment_type, S.trip_type, S.congestion_surcharge);
            """,
            use_legacy_sql=False,
            location=GCP_LOCATION,
        )

        bq_green_tripdata >> bq_green_table_ext >> bq_green_table_tmp >> bq_green_merge

    # Task to clean up local file
    cleanup = PythonOperator(
        task_id='cleanup_local_file',
        python_callable=cleanup_local_file,
        trigger_rule='none_failed_or_skipped',  # Execute even if one branch was skipped
    )

    # Define the DAG flow
    extract >> upload_to_gcs >> branch_task
    branch_task >> [yellow_pipeline, green_pipeline]
    [yellow_pipeline, green_pipeline] >> cleanup
